#############################################################################
# Makefile for building: AUTSat_TMS570.app/Contents/MacOS/AUTSat_TMS570
# Generated by qmake (2.01a) (Qt 4.8.0) on: Tue Nov 8 01:44:06 2011
# Project:  AUTSat_TMS570.pro
# Template: app
# Command: /Developer/Qt/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile AUTSat_TMS570.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.2
CXX           = g++-4.2
DEFINES       = 
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 -I.
LINK          = g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS)    
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/Qt/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = TMS570Board.cpp \
		SPIDriver.cpp \
		GIODriver.cpp \
		FlashDriver.cpp 
OBJECTS       = TMS570Board.o \
		SPIDriver.o \
		GIODriver.o \
		FlashDriver.o
DIST          = /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		AUTSat_TMS570.pro
QMAKE_TARGET  = AUTSat_TMS570
DESTDIR       = 
TARGET        = AUTSat_TMS570.app/Contents/MacOS/AUTSat_TMS570

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile AUTSat_TMS570.app/Contents/PkgInfo AUTSat_TMS570.app/Contents/Resources/empty.lproj AUTSat_TMS570.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) AUTSat_TMS570.app/Contents/MacOS/ || $(MKDIR) AUTSat_TMS570.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AUTSat_TMS570.pro  /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42/qmake.conf /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile AUTSat_TMS570.pro
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42 CONFIG+=declarative_debug -o Makefile AUTSat_TMS570.pro

AUTSat_TMS570.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) AUTSat_TMS570.app/Contents || $(MKDIR) AUTSat_TMS570.app/Contents 
	@$(DEL_FILE) AUTSat_TMS570.app/Contents/PkgInfo
	@echo "APPL????" >AUTSat_TMS570.app/Contents/PkgInfo
AUTSat_TMS570.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) AUTSat_TMS570.app/Contents/Resources || $(MKDIR) AUTSat_TMS570.app/Contents/Resources 
	@touch AUTSat_TMS570.app/Contents/Resources/empty.lproj
	
AUTSat_TMS570.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) AUTSat_TMS570.app/Contents || $(MKDIR) AUTSat_TMS570.app/Contents 
	@$(DEL_FILE) AUTSat_TMS570.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,AUTSat_TMS570,g" -e "s,@TYPEINFO@,????,g" /Developer/Qt/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++42/Info.plist.app >AUTSat_TMS570.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/AUTSat_TMS5701.0.0 || $(MKDIR) .tmp/AUTSat_TMS5701.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AUTSat_TMS5701.0.0/ && (cd `dirname .tmp/AUTSat_TMS5701.0.0` && $(TAR) AUTSat_TMS5701.0.0.tar AUTSat_TMS5701.0.0 && $(COMPRESS) AUTSat_TMS5701.0.0.tar) && $(MOVE) `dirname .tmp/AUTSat_TMS5701.0.0`/AUTSat_TMS5701.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AUTSat_TMS5701.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r AUTSat_TMS570.app
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

TMS570Board.o: TMS570Board.cpp TMS570Board.h \
		FlashDriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TMS570Board.o TMS570Board.cpp

SPIDriver.o: SPIDriver.cpp SPIDriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SPIDriver.o SPIDriver.cpp

GIODriver.o: GIODriver.cpp GIODriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GIODriver.o GIODriver.cpp

FlashDriver.o: FlashDriver.cpp FlashDriver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlashDriver.o FlashDriver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

